### ISSUE TITLE
Proper Attribution & License check

### ISSUE THREAD

**Issue by itdependsnetworks** [classy-python/ccbv#222]
Hi, based on your work, I have put together: https://github.com/itdependsnetworks/mkdocs-python-classy

It's basically using your inspector logic, but letting mkdocs manage everything else. I wanted to ensure that I have correctly provided attribution and license

You can see the associated documentation at:
- https://github.com/itdependsnetworks/mkdocs-python-classy/blob/main/README.md#attribution
- https://github.com/itdependsnetworks/mkdocs-python-classy/blob/main/NOTICE
- https://github.com/itdependsnetworks/mkdocs-python-classy/blob/main/LICENSE
- https://github.com/itdependsnetworks/mkdocs-python-classy/blob/main/docs/dev/attribution.md

**Comment by meshy** [comment]
Thank you for the attribution. As far as I can tell this is a good approach. Good luck with the project!
