### ISSUE TITLE
Add forms

### ISSUE THREAD

**Issue by suspiciousRaccoon** [classy-python/ccbv#230]
If I want to know what happens in `form.is_valid()` , for example in the `post()` method of [UpdateView](https://ccbv.co.uk/projects/Django/5.0/django.views.generic.edit/UpdateView/#post) I need to look at the source code directly and try to piece what calls what. Adding forms to the site would fix this problem.

**Comment by meshy** [comment]
Thanks for the suggestion! You should be able to find documentation on the forms at https://cdf.9vo.lt/

I hope to expand the information on this website at some point in future, but for now please use that alternative.
